import type { NewsPost, Event, GalleryImage} from "@prisma/client";

export const fallbackNews: NewsPost[] = [
  {
    id: "news-1",
    slug: "kuerbisfest-auf-dem-irlenhof",
    title: "Kürbisfest auf dem Irlenhof",
    excerpt:
      "Zum zweiten Mal durfte der Musikverein in diesem Jahr das Kürbisfest auf dem Irlenhof in Ferndorf begleiten.",
    content:
      "Zum zweiten Mal durfte der Musikverein in diesem Jahr das Kürbisfest auf dem Irlenhof in Ferndorf begleiten. Es war eine stimmungsvolle Veranstaltung mit vielen Besucherinnen und Besuchern.",
    publishedAt: new Date("2023-10-21T12:00:00Z"),
    isPublished: true,
    coverImage: null,
    createdAt: new Date("2023-10-21"),
    updatedAt: new Date("2023-10-21"),
  },
  {
    id: "news-2",
    slug: "fruehschoppen-zum-1-mai",
    title: "Frühschoppen zum 1. Mai",
    excerpt:
      "Bei gutem Wetter gab es ein buntes Programm aus klassischer und moderner Blasmusik.",
    content:
      "Beim traditionellen Frühschoppen gab es neben Bier, Würstchen und Pizza ein buntes Programm aus klassischer und moderner Blasmusik.",
    publishedAt: new Date("2023-05-08T12:00:00Z"),
    isPublished: true,
    coverImage: null,
    createdAt: new Date("2023-10-21"),
    updatedAt: new Date("2023-10-21"),
  },
  {
    id: "news-3",
    slug: "fruehlingskonzert-in-hilchenbach",
    title: "Frühlingskonzert in Hilchenbach",
    excerpt:
      "Das Frühlingskonzert bot einen abwechslungsreichen Mix aus traditioneller Literatur und moderner Musik.",
    content:
      "Das Frühlingskonzert fand in der Aula der Carl-Krämer-Realschule statt und bot ein abwechslungsreiches Programm mit Beiträgen aller Jugendgruppen.",
    publishedAt: new Date("2023-05-08T16:00:00Z"),
    isPublished: true,
    coverImage: null,
    createdAt: new Date("2023-10-21"),
    updatedAt: new Date("2023-10-21"),
  },
];

export const fallbackEvents: Event[] = [
  {
    id: "event-1",
    slug: "fruehlingskonzert-2027",
    title: "Frühlingskonzert",
    description: null,
    location: "Hilchenbach",
    startsAt: new Date("2027-03-20T19:00:00+01:00"),
    endsAt: new Date("2027-03-20T22:00:00+01:00"),
    isPublished: true,
    isHidden: false,
    externalUid: null,
    categories: [],
    exclusionReason: null,
    sourceId: null,
    lastImportedAt: null,
    overrideTitle: null,
    overrideDescription: null,
    overrideLocation: null,
    overrideImageUrl: null,
    createdAt: new Date("2027-01-01T00:00:00+01:00"),
    updatedAt: new Date("2027-01-01T00:00:00+01:00"),
  },
  {
    id: "event-2",
    slug: "maibaum-aufstellen-2026",
    title: "Maibaum Aufstellen",
    description: null,
    location: "Müsen",
    startsAt: new Date("2026-04-30T18:00:00+02:00"),
    endsAt: new Date("2026-04-30T20:00:00+02:00"),
    isPublished: true,
    isHidden: false,
    externalUid: null,
    categories: [],
    exclusionReason: null,
    sourceId: null,
    lastImportedAt: null,
    overrideTitle: null,
    overrideDescription: null,
    overrideLocation: null,
    overrideImageUrl: null,
    createdAt: new Date("2026-01-01T00:00:00+01:00"),
    updatedAt: new Date("2026-01-01T00:00:00+01:00"),
  },
  {
    id: "event-3",
    slug: "fruehschoppen-zum-1-mai-2026",
    title: "Frühschoppen zum 1. Mai",
    description: null,
    location: "Müsen",
    startsAt: new Date("2026-05-01T11:00:00+02:00"),
    endsAt: new Date("2026-05-01T16:00:00+02:00"),
    isPublished: true,
    isHidden: false,
    externalUid: null,
    categories: [],
    exclusionReason: null,
    sourceId: null,
    lastImportedAt: null,
    overrideTitle: null,
    overrideDescription: null,
    overrideLocation: null,
    overrideImageUrl: null,
    createdAt: new Date("2026-01-01T00:00:00+01:00"),
    updatedAt: new Date("2026-01-01T00:00:00+01:00"),
  },
];

export const fallbackGalleryImages: GalleryImage[] = [
   {
    id: "gallery-1",
    title: "Konzert",
    slug: "konzert",
    imageUrl: "",
    altText: "Konzert",
    caption: "Vereinsleben",
    isPublished: true,
    createdAt: new Date("2026-01-01T00:00:00+01:00"),
    updatedAt: new Date("2026-01-01T00:00:00+01:00"),
  },
  {
    id: "gallery-2",
    title: "Frühschoppen",
    slug: "fruehschoppen",
    imageUrl: "",
    altText: "Frühschoppen",
    caption: "Vereinsleben",
    isPublished: true,
    createdAt: new Date("2026-01-01T00:00:00+01:00"),
    updatedAt: new Date("2026-01-01T00:00:00+01:00"),
  },
  {
    id: "gallery-3",
    title: "Jugendorchester",
    slug: "jugendorchester",
    imageUrl: "",
    altText: "Jugendorchester",
    caption: "Jugend",
    isPublished: true,
    createdAt: new Date("2026-01-01T00:00:00+01:00"),
    updatedAt: new Date("2026-01-01T00:00:00+01:00"),
  },
];
